"""Render normalized sessions as stable Markdown notes in an Obsidian Vault."""

from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from datetime import UTC, datetime
from pathlib import Path, PurePosixPath
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from .adapters import Message, SessionDocument, build_session_document
from .core import Config, EventStore

GENERATED_MARKER = (
    "<!-- generated by agent-session-exporter; edits may be overwritten -->"
)
SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9._-]+")


def _yaml_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(str(value), ensure_ascii=False)


def _clean_name(value: str, fallback: str) -> str:
    cleaned = SAFE_NAME_RE.sub("-", value.strip()).strip("-._").lower()
    return (cleaned or fallback)[:80]


def _parse_date(value: str, timezone_name: str) -> datetime:
    normalized = value.replace("Z", "+00:00")
    try:
        date = datetime.fromisoformat(normalized)
    except ValueError:
        date = datetime.now(UTC)
    if date.tzinfo is None:
        date = date.replace(tzinfo=UTC)
    if timezone_name == "UTC":
        timezone = UTC
    else:
        try:
            timezone = ZoneInfo(timezone_name)
        except ZoneInfoNotFoundError as error:
            raise ValueError(f"Unknown path_timezone: {timezone_name}") from error
    return date.astimezone(timezone)


def _first_user_text(messages: list[Message]) -> str:
    return next(
        (message.text for message in messages if message.role == "user"),
        "",
    )


def session_title(document: SessionDocument) -> str:
    """Return a compact human-readable note title."""
    imported = document.metadata.get("imported_title")
    if imported:
        return str(imported).strip()[:120]
    first_user = " ".join(_first_user_text(document.messages).split())
    if first_user:
        return first_user[:120]
    return f"{document.source} session — {document.project}"


def render_markdown(document: SessionDocument) -> str:
    """Render a session document to Obsidian-compatible Markdown."""
    title = session_title(document)
    frontmatter = {
        "title": title,
        "source": document.source,
        "session_id": document.session_id,
        "device": document.device_id,
        "project": document.project,
        "repository": document.repository,
        "branch": document.branch,
        "cwd": document.cwd,
        "started_at": document.started_at,
        "ended_at": document.ended_at,
        "status": document.status,
        "archived_at": document.ended_at,
        "tags": "[ai-session]",
    }
    lines = ["---"]
    for key, value in frontmatter.items():
        if value not in ("", None):
            if key == "tags":
                lines.append("tags:")
                lines.append("  - ai-session")
            else:
                lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.extend(["---", "", GENERATED_MARKER, "", f"# {title}", ""])

    if not document.messages:
        lines.extend(
            [
                (
                    "> This environment did not expose conversation text. "
                    "Only session metadata was available."
                ),
                "",
            ]
        )
    else:
        role_labels = {
            "user": "User",
            "assistant": "Assistant",
            "system": "System",
        }
        for message in document.messages:
            label = role_labels.get(message.role, message.role.title())
            lines.append(f"## {label}")
            lines.append("")
            if message.timestamp:
                lines.append(f"*{message.timestamp}*")
                lines.append("")
            lines.append(message.text.rstrip())
            lines.append("")

    diff = document.metadata.get("diff")
    if isinstance(diff, str) and diff.strip():
        lines.extend(["## Diff", "", "```diff", diff.rstrip(), "```", ""])

    metadata = {
        key: value
        for key, value in document.metadata.items()
        if key not in {"diff", "imported_title", "transcript_path", "git"}
        and value not in ("", None)
    }
    if metadata:
        lines.extend(["## Metadata", ""])
        for key, value in sorted(metadata.items()):
            display = " ".join(str(value).split()).replace("`", "\\`")
            lines.append(f"- {key}: `{display}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _new_note_path(
    document: SessionDocument,
    destination: str,
    timezone_name: str,
) -> PurePosixPath:
    date = _parse_date(document.started_at, timezone_name)
    source = _clean_name(document.source, "agent")
    project = _clean_name(document.project, "unknown")
    readable_id = _clean_name(document.session_id, "session")[:8]
    identity_hash = hashlib.sha256(
        f"{document.device_id}\x1f{document.session_id}".encode()
    ).hexdigest()[:6]
    short_id = f"{readable_id}-{identity_hash}"
    filename = f"{date:%Y-%m-%d-%H%M}-{source}-{project}-{short_id}.md"
    return PurePosixPath(destination) / f"{date:%Y}" / f"{date:%m}" / filename


def _safe_note_path(vault: Path, note_path: PurePosixPath) -> Path:
    candidate = (vault / Path(*note_path.parts)).resolve()
    vault_resolved = vault.resolve()
    if candidate != vault_resolved and vault_resolved not in candidate.parents:
        raise ValueError(f"Refusing to write outside Vault: {candidate}")
    return candidate


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=f".{path.name}.",
        dir=path.parent,
        text=True,
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def _sync_stored_session(
    config: Config,
    store: EventStore,
    source: str,
    device_id: str,
    session_id: str,
) -> bool:
    if config.vault_path is None:
        raise ValueError("vault_path is not configured. Run `ase init --vault PATH`.")
    events = store.session_events(source, device_id, session_id)
    if not events:
        return False
    document = build_session_document(events)
    content = render_markdown(document)
    content_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
    key = store.session_key(source, device_id, session_id)
    state = store.get_render_state(key)
    if state is not None:
        note_path = PurePosixPath(str(state["note_path"]))
        if str(state["content_hash"]) == content_hash:
            return False
    else:
        note_path = _new_note_path(
            document,
            config.destination,
            config.path_timezone,
        )
    target = _safe_note_path(config.vault_path, note_path)
    _atomic_write(target, content)
    store.set_render_state(key, content_hash, note_path.as_posix())
    return True


def sync_session(
    config: Config,
    source: str,
    device_id: str,
    session_id: str,
) -> bool:
    """Render one changed session immediately after local hook capture."""
    if config.vault_path is None:
        return False
    config.vault_path.mkdir(parents=True, exist_ok=True)
    with EventStore(config.state_dir) as store:
        return _sync_stored_session(
            config,
            store,
            source,
            device_id,
            session_id,
        )


def sync_vault(config: Config) -> tuple[int, int]:
    """Render all changed sessions and return written and unchanged counts."""
    if config.vault_path is None:
        raise ValueError("vault_path is not configured. Run `ase init --vault PATH`.")
    vault = config.vault_path
    vault.mkdir(parents=True, exist_ok=True)
    written = 0
    unchanged = 0

    with EventStore(config.state_dir) as store:
        for source, device_id, session_id in store.list_session_keys():
            if _sync_stored_session(
                config,
                store,
                source,
                device_id,
                session_id,
            ):
                written += 1
            else:
                unchanged += 1
    return written, unchanged
