"""Render normalized sessions as stable Markdown notes in an Obsidian Vault."""

from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path, PurePosixPath

from .adapters import Message, SessionDocument, build_session_document
from .core import Config, EventStore

GENERATED_MARKER = (
    "<!-- generated by agent-session-exporter; edits may be overwritten -->"
)
SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9._-]+")
YEAR_RE = re.compile(r"^[0-9]{4}$")
MONTH_RE = re.compile(r"^[0-9]{2}$")


@dataclass(frozen=True)
class RenderStateMigration:
    """One safe note move or render-state rebind."""

    session_key: str
    operation: str
    old_path: PurePosixPath
    new_path: PurePosixPath


def _yaml_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(str(value), ensure_ascii=False)


def _clean_name(value: str, fallback: str) -> str:
    cleaned = SAFE_NAME_RE.sub("-", value.strip()).strip("-._").lower()
    return (cleaned or fallback)[:80]


def _parse_date(value: str) -> datetime:
    normalized = value.replace("Z", "+00:00")
    try:
        return datetime.fromisoformat(normalized)
    except ValueError:
        return datetime.now().astimezone()


def _first_user_text(messages: list[Message]) -> str:
    return next(
        (message.text for message in messages if message.role == "user"),
        "",
    )


def session_title(document: SessionDocument) -> str:
    """Return a compact human-readable note title."""
    imported = document.metadata.get("imported_title")
    if imported:
        return str(imported).strip()[:120]
    first_user = " ".join(_first_user_text(document.messages).split())
    if first_user:
        return first_user[:120]
    return f"{document.source} session — {document.project}"


def render_markdown(document: SessionDocument) -> str:
    """Render a session document to Obsidian-compatible Markdown."""
    title = session_title(document)
    frontmatter = {
        "title": title,
        "source": document.source,
        "session_id": document.session_id,
        "device": document.device_id,
        "project": document.project,
        "repository": document.repository,
        "branch": document.branch,
        "cwd": document.cwd,
        "started_at": document.started_at,
        "ended_at": document.ended_at,
        "status": document.status,
        "archived_at": document.ended_at,
        "tags": "[ai-session]",
    }
    lines = ["---"]
    for key, value in frontmatter.items():
        if value not in ("", None):
            if key == "tags":
                lines.append("tags:")
                lines.append("  - ai-session")
            else:
                lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.extend(["---", "", GENERATED_MARKER, "", f"# {title}", ""])

    if not document.messages:
        lines.extend(
            [
                (
                    "> This environment did not expose conversation text. "
                    "Only session metadata was available."
                ),
                "",
            ]
        )
    else:
        role_labels = {
            "user": "User",
            "assistant": "Assistant",
            "system": "System",
        }
        for message in document.messages:
            label = role_labels.get(message.role, message.role.title())
            lines.append(f"## {label}")
            lines.append("")
            if message.timestamp:
                lines.append(f"*{message.timestamp}*")
                lines.append("")
            lines.append(message.text.rstrip())
            lines.append("")

    diff = document.metadata.get("diff")
    if isinstance(diff, str) and diff.strip():
        lines.extend(["## Diff", "", "```diff", diff.rstrip(), "```", ""])

    metadata = {
        key: value
        for key, value in document.metadata.items()
        if key not in {"diff", "imported_title", "transcript_path", "git"}
        and value not in ("", None)
    }
    if metadata:
        lines.extend(["## Metadata", ""])
        for key, value in sorted(metadata.items()):
            display = " ".join(str(value).split()).replace("`", "\\`")
            lines.append(f"- {key}: `{display}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _new_note_path(document: SessionDocument, destination: str) -> PurePosixPath:
    date = _parse_date(document.started_at)
    source = _clean_name(document.source, "agent")
    project = _clean_name(document.project, "unknown")
    readable_id = _clean_name(document.session_id, "session")[:8]
    identity_hash = hashlib.sha256(
        f"{document.device_id}\x1f{document.session_id}".encode()
    ).hexdigest()[:6]
    short_id = f"{readable_id}-{identity_hash}"
    filename = f"{date:%Y-%m-%d-%H%M}-{source}-{project}-{short_id}.md"
    return PurePosixPath(destination) / f"{date:%Y}" / f"{date:%m}" / filename


def _safe_note_path(vault: Path, note_path: PurePosixPath) -> Path:
    candidate = (vault / Path(*note_path.parts)).resolve()
    vault_resolved = vault.resolve()
    if candidate != vault_resolved and vault_resolved not in candidate.parents:
        raise ValueError(f"Refusing to write outside Vault: {candidate}")
    return candidate


def _is_in_destination(note_path: PurePosixPath, destination: str) -> bool:
    destination_path = PurePosixPath(destination)
    return destination_path in note_path.parents


def _destination_note_path(
    note_path: PurePosixPath,
    destination: str,
) -> PurePosixPath:
    if len(note_path.parts) < 3:
        raise ValueError(f"Render path has no YYYY/MM suffix: {note_path}")
    year, month, filename = note_path.parts[-3:]
    if not YEAR_RE.fullmatch(year) or not MONTH_RE.fullmatch(month):
        raise ValueError(f"Render path has no YYYY/MM suffix: {note_path}")
    if not filename.endswith(".md"):
        raise ValueError(f"Render path is not Markdown: {note_path}")
    return PurePosixPath(destination) / year / month / filename


def _verified_generated_hash(path: Path, expected_hash: str) -> str:
    try:
        content = path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        return f"cannot read {path}: {error}"
    if GENERATED_MARKER not in content:
        return f"refusing non-generated note: {path}"
    actual_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
    if actual_hash != expected_hash:
        return f"content differs from render state: {path}"
    return ""


def render_state_path_issues(config: Config) -> list[str]:
    """Return missing and out-of-destination paths without changing state."""
    if config.vault_path is None:
        return []
    issues: list[str] = []
    with EventStore(config.state_dir) as store:
        for state in store.list_render_states():
            note_path = PurePosixPath(str(state["note_path"]))
            try:
                target = _safe_note_path(config.vault_path, note_path)
            except ValueError as error:
                issues.append(str(error))
                continue
            reasons: list[str] = []
            if not target.is_file():
                reasons.append("missing")
            if not _is_in_destination(note_path, config.destination):
                reasons.append("outside destination")
            if reasons:
                issues.append(f"{note_path}: {', '.join(reasons)}")
    return issues


def migrate_render_state(
    config: Config,
    *,
    apply: bool = False,
) -> tuple[list[RenderStateMigration], list[str]]:
    """Plan or apply safe migration of generated notes to the destination."""
    if config.vault_path is None:
        raise ValueError("vault_path is not configured. Run `ase init --vault PATH`.")
    migrations: list[RenderStateMigration] = []
    errors: list[str] = []
    with EventStore(config.state_dir) as store:
        for state in store.list_render_states():
            old_note_path = PurePosixPath(str(state["note_path"]))
            try:
                old_target = _safe_note_path(config.vault_path, old_note_path)
                if (
                    _is_in_destination(old_note_path, config.destination)
                    and old_target.is_file()
                ):
                    continue
                new_note_path = _destination_note_path(
                    old_note_path,
                    config.destination,
                )
                new_target = _safe_note_path(config.vault_path, new_note_path)
            except ValueError as error:
                errors.append(str(error))
                continue
            expected_hash = str(state["content_hash"])
            operation = ""
            if new_target.is_file():
                problem = _verified_generated_hash(new_target, expected_hash)
                if problem:
                    errors.append(problem)
                    continue
                operation = "rebind"
            elif old_target.is_file():
                problem = _verified_generated_hash(old_target, expected_hash)
                if problem:
                    errors.append(problem)
                    continue
                operation = "move"
            else:
                errors.append(
                    f"cannot locate generated note: {old_note_path} or {new_note_path}"
                )
                continue

            migration = RenderStateMigration(
                session_key=str(state["session_key"]),
                operation=operation,
                old_path=old_note_path,
                new_path=new_note_path,
            )
            migrations.append(migration)
            if not apply:
                continue
            if operation == "move":
                new_target.parent.mkdir(parents=True, exist_ok=True)
                os.replace(old_target, new_target)
            store.set_render_state(
                migration.session_key,
                expected_hash,
                new_note_path.as_posix(),
            )
    return migrations, errors


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=f".{path.name}.",
        dir=path.parent,
        text=True,
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def _sync_stored_session(
    config: Config,
    store: EventStore,
    source: str,
    device_id: str,
    session_id: str,
) -> bool:
    if config.vault_path is None:
        raise ValueError("vault_path is not configured. Run `ase init --vault PATH`.")
    events = store.session_events(source, device_id, session_id)
    if not events:
        return False
    document = build_session_document(events)
    content = render_markdown(document)
    content_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
    key = store.session_key(source, device_id, session_id)
    state = store.get_render_state(key)
    if state is not None:
        note_path = PurePosixPath(str(state["note_path"]))
        if str(state["content_hash"]) == content_hash:
            return False
    else:
        note_path = _new_note_path(document, config.destination)
    target = _safe_note_path(config.vault_path, note_path)
    _atomic_write(target, content)
    store.set_render_state(key, content_hash, note_path.as_posix())
    return True


def sync_session(
    config: Config,
    source: str,
    device_id: str,
    session_id: str,
) -> bool:
    """Render one changed session immediately after local hook capture."""
    if config.vault_path is None:
        return False
    config.vault_path.mkdir(parents=True, exist_ok=True)
    with EventStore(config.state_dir) as store:
        return _sync_stored_session(
            config,
            store,
            source,
            device_id,
            session_id,
        )


def sync_vault(config: Config) -> tuple[int, int]:
    """Render all changed sessions and return written and unchanged counts."""
    if config.vault_path is None:
        raise ValueError("vault_path is not configured. Run `ase init --vault PATH`.")
    vault = config.vault_path
    vault.mkdir(parents=True, exist_ok=True)
    written = 0
    unchanged = 0

    with EventStore(config.state_dir) as store:
        for source, device_id, session_id in store.list_session_keys():
            if _sync_stored_session(
                config,
                store,
                source,
                device_id,
                session_id,
            ):
                written += 1
            else:
                unchanged += 1
    return written, unchanged
