"""Render normalized sessions as stable Markdown notes in an Obsidian Vault."""

from __future__ import annotations

import hashlib
import json
import os
import re
import tempfile
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from pathlib import Path, PurePosixPath
from zoneinfo import ZoneInfo, ZoneInfoNotFoundError

from .adapters import Message, SessionDocument, build_session_document
from .core import Config, EventStore, now_iso
from .redaction import redact_value, session_identity

GENERATED_MARKER = (
    "<!-- generated by agent-session-exporter; edits may be overwritten -->"
)
SAFE_NAME_RE = re.compile(r"[^A-Za-z0-9._-]+")
YEAR_RE = re.compile(r"^[0-9]{4}$")
MONTH_RE = re.compile(r"^[0-9]{2}$")
CONTROL_TITLE_PREFIXES = (
    "# agents.md instructions",
    "<environment_context>",
    "<command-",
    "<recommended_plugins>",
)
NOTE_IDENTITY_KEYS = ("source", "session_id", "device", "identity_key")


@dataclass(frozen=True)
class RenderStateMigration:
    """One safe note move, rebind, or generated-target replacement."""

    session_key: str
    operation: str
    old_path: PurePosixPath
    new_path: PurePosixPath
    backup_path: PurePosixPath | None = None


def _yaml_scalar(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return json.dumps(value)
    return json.dumps(str(value), ensure_ascii=False)


def _clean_name(value: str, fallback: str) -> str:
    cleaned = SAFE_NAME_RE.sub("-", value.strip()).strip("-._").lower()
    return (cleaned or fallback)[:80]


def _parse_date(value: str, timezone_name: str) -> datetime:
    normalized = value.replace("Z", "+00:00")
    try:
        date = datetime.fromisoformat(normalized)
    except ValueError:
        date = datetime.now(UTC)
    if date.tzinfo is None:
        date = date.replace(tzinfo=UTC)
    if timezone_name == "UTC":
        timezone = UTC
    else:
        try:
            timezone = ZoneInfo(timezone_name)
        except ZoneInfoNotFoundError as error:
            raise ValueError(f"Unknown path_timezone: {timezone_name}") from error
    try:
        return date.astimezone(timezone)
    except OverflowError:
        # Match the fallback for malformed timestamps, without rewriting stored events.
        return datetime.now(timezone)


def _title_candidate(value: object) -> str:
    text = " ".join(str(value).split())
    if not text:
        return ""
    if text.casefold().startswith(CONTROL_TITLE_PREFIXES):
        return ""
    return text[:120]


def session_title(document: SessionDocument) -> str:
    """Return a compact human-readable note title."""
    imported = document.metadata.get("imported_title")
    if imported:
        return str(imported).strip()[:120]
    title_hint = _title_candidate(document.metadata.get("title_hint", ""))
    if title_hint:
        return title_hint
    for message in document.messages:
        if message.role != "user":
            continue
        candidate = _title_candidate(message.text)
        if candidate:
            return candidate
    return f"{document.source} session — {document.project}"


def render_markdown(
    document: SessionDocument,
    *,
    rendered_at: str = "",
) -> str:
    """Render a session document to Obsidian-compatible Markdown."""
    title = session_title(document)
    frontmatter = {
        "title": title,
        "source": document.source,
        "session_id": document.session_id,
        "device": document.device_id,
        "identity_key": document.metadata.get("identity_key", ""),
        "project": document.project,
        "repository": document.repository,
        "branch": document.branch,
        "cwd": document.cwd,
        "started_at": document.started_at,
        "ended_at": document.ended_at,
        "updated_at": document.ended_at,
        "rendered_at": rendered_at,
        "status": document.status,
        "content_kind": (
            "transcript" if document.messages else "metadata_only"
        ),
        "message_count": len(document.messages),
        "event_count": document.event_count,
        "revision": document.revision,
        "archived_at": (
            document.ended_at
            if document.status in {"completed", "failed"}
            else ""
        ),
        "tags": "[ai-session]",
    }
    lines = ["---"]
    for key, value in frontmatter.items():
        if value not in ("", None):
            if key == "tags":
                lines.append("tags:")
                lines.append("  - ai-session")
            else:
                lines.append(f"{key}: {_yaml_scalar(value)}")
    lines.extend(["---", "", GENERATED_MARKER, "", f"# {title}", ""])

    if not document.messages:
        lines.extend(
            [
                (
                    "> This environment did not expose conversation text. "
                    "Only session metadata was available."
                ),
                "",
            ]
        )
    else:
        role_labels = {
            "user": "User",
            "assistant": "Assistant",
            "system": "System",
        }
        for message in document.messages:
            label = role_labels.get(message.role, message.role.title())
            lines.append(f"## {label}")
            lines.append("")
            if message.timestamp:
                lines.append(f"*{message.timestamp}*")
                lines.append("")
            lines.append(message.text.rstrip())
            lines.append("")

    diff = document.metadata.get("diff")
    if isinstance(diff, str) and diff.strip():
        lines.extend(["## Diff", "", "```diff", diff.rstrip(), "```", ""])

    metadata = {
        key: value
        for key, value in document.metadata.items()
        if key
        not in {"diff", "imported_title", "title_hint", "transcript_path", "git", "identity_key"}
        and value not in ("", None)
    }
    if metadata:
        lines.extend(["## Metadata", ""])
        for key, value in sorted(metadata.items()):
            display = " ".join(str(value).split()).replace("`", "\\`")
            lines.append(f"- {key}: `{display}`")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def _new_note_path(
    document: SessionDocument,
    destination: str,
    timezone_name: str,
    identity_key: str = "",
) -> PurePosixPath:
    date = _parse_date(document.started_at, timezone_name)
    source = _clean_name(document.source, "agent")
    project = _clean_name(document.project, "unknown")
    readable_id = _clean_name(document.session_id, "session")[:8]
    identity_hash = identity_key[:12] if identity_key else hashlib.sha256(
        f"{document.device_id}\x1f{document.session_id}".encode()
    ).hexdigest()[:6]
    short_id = f"{readable_id}-{identity_hash}"
    filename = f"{date:%Y-%m-%d-%H%M}-{source}-{project}-{short_id}.md"
    return PurePosixPath(destination) / f"{date:%Y}" / f"{date:%m}" / filename


def _safe_note_path(vault: Path, note_path: PurePosixPath) -> Path:
    candidate = (vault / Path(*note_path.parts)).resolve()
    vault_resolved = vault.resolve()
    if candidate != vault_resolved and vault_resolved not in candidate.parents:
        raise ValueError(f"Refusing to write outside Vault: {candidate}")
    return candidate


def _is_in_destination(note_path: PurePosixPath, destination: str) -> bool:
    destination_path = PurePosixPath(destination)
    return destination_path in note_path.parents


def _destination_note_path(
    note_path: PurePosixPath,
    destination: str,
) -> PurePosixPath:
    if len(note_path.parts) < 3:
        raise ValueError(f"Render path has no YYYY/MM suffix: {note_path}")
    year, month, filename = note_path.parts[-3:]
    if not YEAR_RE.fullmatch(year) or not MONTH_RE.fullmatch(month):
        raise ValueError(f"Render path has no YYYY/MM suffix: {note_path}")
    if not filename.endswith(".md"):
        raise ValueError(f"Render path is not Markdown: {note_path}")
    return PurePosixPath(destination) / year / month / filename


def _generated_note(path: Path) -> tuple[str, str, str]:
    try:
        content = path.read_bytes().decode("utf-8")
    except (OSError, UnicodeError) as error:
        return "", "", f"cannot read {path}: {error}"
    if GENERATED_MARKER not in content:
        return "", "", f"refusing non-generated note: {path}"
    actual_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
    return content, actual_hash, ""


def _verified_generated_hash(path: Path, expected_hash: str) -> str:
    _, actual_hash, problem = _generated_note(path)
    if problem:
        return problem
    if actual_hash != expected_hash:
        return f"content differs from render state: {path}"
    return ""


def _generated_note_parts(content: str) -> tuple[list[str], str] | None:
    """Split frontmatter using only the LF delimiters emitted by the renderer."""
    opening = "---\n"
    closing = "\n---\n"
    if not content.startswith(opening):
        return None
    end = content.find(closing, len(opening))
    if end < 0:
        return None
    lines = content[len(opening) : end].split("\n")
    return lines, content[end + len(closing) :]


def _generated_note_identity(content: str) -> tuple[str, str, str, str] | None:
    parts = _generated_note_parts(content)
    if parts is None:
        return None
    lines, _ = parts
    values: dict[str, str] = {"identity_key": ""}  # Older generated notes lack provenance.
    for line in lines:
        key, separator, encoded = line.partition(":")
        if not separator or key not in NOTE_IDENTITY_KEYS:
            continue
        try:
            value = json.loads(encoded.strip())
        except (json.JSONDecodeError, TypeError):
            return None
        if not isinstance(value, str):
            return None
        values[key] = str(value)
    if any(key not in values for key in NOTE_IDENTITY_KEYS):
        return None
    return tuple(values[key] for key in NOTE_IDENTITY_KEYS)


def _generated_note_body(content: str) -> str | None:
    """Return content after generated frontmatter, marker, and title."""
    parts = _generated_note_parts(content)
    if parts is None:
        return None
    lines, rendered = parts
    title: str | None = None
    for line in lines:
        key, separator, encoded = line.partition(":")
        if separator and key == "title":
            try:
                value = json.loads(encoded.strip())
            except (json.JSONDecodeError, TypeError):
                return None
            if not isinstance(value, str):
                return None
            title = value
    if title is None:
        return None
    prefix = f"\n{GENERATED_MARKER}\n\n# {title}\n\n"
    if not rendered.startswith(prefix):
        return None
    return rendered[len(prefix) :]


def _stale_backup_path(
    note_path: PurePosixPath,
    content_hash: str,
) -> PurePosixPath:
    filename = f".{note_path.stem}.stale-{content_hash[:12]}{note_path.suffix}"
    return note_path.with_name(filename)


def _replace_with_backup(old: Path, new: Path, backup: Path) -> None:
    """Replace a stale target and roll back only a verified incomplete move."""
    os.replace(new, backup)
    try:
        os.replace(old, new)
    except BaseException as error:
        if not old.is_file() or new.exists():
            raise
        try:
            os.replace(backup, new)
        except OSError as rollback_error:
            raise OSError(
                f"cannot move {old} to {new}; rollback also failed: "
                f"{rollback_error}"
            ) from error
        raise


def render_state_path_issues(config: Config) -> list[str]:
    """Return missing and out-of-destination paths without changing state."""
    if config.vault_path is None:
        return []
    issues: list[str] = []
    with EventStore(config.state_dir) as store:
        for state in store.list_render_states():
            note_path = PurePosixPath(str(state["note_path"]))
            try:
                target = _safe_note_path(config.vault_path, note_path)
            except ValueError as error:
                issues.append(str(error))
                continue
            reasons: list[str] = []
            if not target.is_file():
                reasons.append("missing")
            if not _is_in_destination(note_path, config.destination):
                reasons.append("outside destination")
            if reasons:
                issues.append(f"{note_path}: {', '.join(reasons)}")
    return issues


def migrate_render_state(
    config: Config,
    *,
    apply: bool = False,
) -> tuple[list[RenderStateMigration], list[str]]:
    """Plan or apply safe migration of generated notes to the destination."""
    if config.vault_path is None:
        raise ValueError("vault_path is not configured. Run `ase init --vault PATH`.")
    migrations: list[RenderStateMigration] = []
    errors: list[str] = []
    with EventStore(config.state_dir) as store:
        for state in store.list_render_states():
            old_note_path = PurePosixPath(str(state["note_path"]))
            try:
                old_target = _safe_note_path(config.vault_path, old_note_path)
                if (
                    _is_in_destination(old_note_path, config.destination)
                    and old_target.is_file()
                ):
                    continue
                new_note_path = _destination_note_path(
                    old_note_path,
                    config.destination,
                )
                new_target = _safe_note_path(config.vault_path, new_note_path)
            except ValueError as error:
                errors.append(str(error))
                continue
            expected_hash = str(state["content_hash"])
            operation = ""
            backup_note_path: PurePosixPath | None = None
            if new_target.is_file():
                new_content, new_hash, problem = _generated_note(new_target)
                if problem:
                    errors.append(problem)
                    continue
                if new_hash == expected_hash:
                    operation = "rebind"
                elif old_target.is_file():
                    old_content, old_hash, problem = _generated_note(old_target)
                    if problem:
                        errors.append(problem)
                        continue
                    if old_hash != expected_hash:
                        errors.append(
                            f"content differs from render state: {old_target}"
                        )
                        continue
                    old_identity = _generated_note_identity(old_content)
                    new_identity = _generated_note_identity(new_content)
                    if old_identity is None or new_identity is None:
                        errors.append(
                            "cannot verify generated note identity: "
                            f"{new_target}"
                        )
                        continue
                    if old_identity != new_identity:
                        errors.append(
                            "refusing generated note for a different session: "
                            f"{new_target}"
                        )
                        continue
                    old_body = _generated_note_body(old_content)
                    new_body = _generated_note_body(new_content)
                    if old_body is None or new_body is None:
                        errors.append(
                            "cannot compare generated note body: "
                            f"{new_target}"
                        )
                        continue
                    if old_body.startswith(new_body):
                        operation = "replace-append-only"
                    else:
                        backup_note_path = _stale_backup_path(
                            new_note_path,
                            new_hash,
                        )
                        backup_target = _safe_note_path(
                            config.vault_path,
                            backup_note_path,
                        )
                        if backup_target.exists():
                            if not backup_target.is_file():
                                errors.append(
                                    "stale backup conflicts: "
                                    f"{backup_target}: not a file"
                                )
                                continue
                            problem = _verified_generated_hash(
                                backup_target,
                                new_hash,
                            )
                            if problem:
                                errors.append(
                                    "stale backup conflicts: "
                                    f"{backup_target}: {problem}"
                                )
                                continue
                        operation = "replace-stale"
                else:
                    errors.append(
                        f"content differs from render state: {new_target}"
                    )
                    continue
            elif old_target.is_file():
                problem = _verified_generated_hash(old_target, expected_hash)
                if problem:
                    errors.append(problem)
                    continue
                operation = "move"
            else:
                errors.append(
                    f"cannot locate generated note: {old_note_path} or {new_note_path}"
                )
                continue

            migration = RenderStateMigration(
                session_key=str(state["session_key"]),
                operation=operation,
                old_path=old_note_path,
                new_path=new_note_path,
                backup_path=backup_note_path,
            )
            if not apply:
                migrations.append(migration)
                continue
            if operation == "move":
                new_target.parent.mkdir(parents=True, exist_ok=True)
                os.replace(old_target, new_target)
            elif operation == "replace-append-only":
                problem = _verified_generated_hash(new_target, new_hash)
                if problem:
                    errors.append(
                        "destination changed during migration: "
                        f"{new_target}: {problem}"
                    )
                    continue
                os.replace(old_target, new_target)
            elif operation == "replace-stale":
                if backup_note_path is None:
                    raise AssertionError("replace-stale migration has no backup path")
                backup_target = _safe_note_path(
                    config.vault_path,
                    backup_note_path,
                )
                backup_target.parent.mkdir(parents=True, exist_ok=True)
                _replace_with_backup(old_target, new_target, backup_target)
            store.set_render_state(
                migration.session_key,
                expected_hash,
                new_note_path.as_posix(),
            )
            migrations.append(migration)
    return migrations, errors


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=f".{path.name}.",
        dir=path.parent,
        text=True,
    )
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def _sync_stored_session(
    config: Config,
    store: EventStore,
    source: str,
    device_id: str,
    session_id: str,
    identity_key: str = "",
) -> bool:
    if config.vault_path is None:
        raise ValueError("vault_path is not configured. Run `ase init --vault PATH`.")
    events = store.session_events(source, device_id, session_id, identity_key)
    if not events:
        return False
    document = build_session_document(events)
    if config.redact:
        # Scan after transcript loading and delta assembly, including legacy DB events.
        values = redact_value(asdict(document))
        values["messages"] = [Message(**message) for message in values["messages"]]
        document = SessionDocument(**values)
    document.metadata["identity_key"] = identity_key or session_identity(device_id, session_id)
    source_content = render_markdown(document)
    source_hash = hashlib.sha256(source_content.encode("utf-8")).hexdigest()
    aliases = store.session_aliases(source, device_id, session_id, identity_key)
    alias_keys = [store.session_key(*alias) for alias in aliases]
    states = [state for alias_key in alias_keys
              if (state := store.get_render_state(alias_key)) is not None]
    # Reuse an existing path even when capture supplied the newly pseudonymized key.
    state = states[0] if states else None
    key = str(state["session_key"]) if state is not None else alias_keys[0]
    if state is not None:
        note_path = PurePosixPath(str(state["note_path"]))
        if str(state["source_hash"]) == source_hash and len(states) == 1:
            return False
    else:
        note_path = _new_note_path(
            document,
            config.destination,
            config.path_timezone,
            identity_key or session_identity(device_id, session_id),
        )
    rendered_at = now_iso()
    content = render_markdown(document, rendered_at=rendered_at)
    content_hash = hashlib.sha256(content.encode("utf-8")).hexdigest()
    target = _safe_note_path(config.vault_path, note_path)
    obsolete_paths: set[Path] = set()
    if len(states) > 1:
        # Repair notes already split by an older exporter, preserving any user edits.
        expected: dict[Path, set[str]] = {}
        for old_state in states:
            path = _safe_note_path(config.vault_path, PurePosixPath(str(old_state["note_path"])))
            expected.setdefault(path, set()).add(str(old_state["content_hash"]))
        for other in store.list_render_states():
            if str(other["session_key"]) in alias_keys:
                continue
            path = _safe_note_path(config.vault_path, PurePosixPath(str(other["note_path"])))
            if path in expected:
                raise ValueError(f"refusing note shared with a different session: {path}")
        for path, hashes in expected.items():
            if not path.exists():
                continue
            old_content, actual_hash, problem = _generated_note(path)
            # A previous attempt may have written the complete note before cleanup/state failed.
            complete_retry = path == target and re.sub(
                r"^rendered_at: [^\n]*\n", "", old_content, count=1, flags=re.MULTILINE,
            ) == source_content
            if problem or (actual_hash not in hashes and not complete_retry):
                raise ValueError(problem or f"content differs from render state: {path}")
            if path != target:
                obsolete_paths.add(path)
    _atomic_write(target, content)
    for path in obsolete_paths:
        path.unlink()
    store.set_render_state(
        key,
        content_hash,
        note_path.as_posix(),
        source_hash=source_hash,
        rendered_at=rendered_at,
        superseded_keys=alias_keys,
    )
    return True


def sync_session(
    config: Config,
    source: str,
    device_id: str,
    session_id: str,
    identity_key: str = "",
) -> bool:
    """Render one changed session immediately after local hook capture."""
    if config.vault_path is None:
        return False
    config.vault_path.mkdir(parents=True, exist_ok=True)
    with EventStore(config.state_dir) as store:
        return _sync_stored_session(
            config,
            store,
            source,
            device_id,
            session_id,
            identity_key,
        )


def sync_vault(config: Config) -> tuple[int, int]:
    """Render all changed sessions and return written and unchanged counts."""
    if config.vault_path is None:
        raise ValueError("vault_path is not configured. Run `ase init --vault PATH`.")
    vault = config.vault_path
    vault.mkdir(parents=True, exist_ok=True)
    written = 0
    unchanged = 0

    with EventStore(config.state_dir) as store:
        for source, device_id, session_id, identity_key in store.list_session_keys():
            if _sync_stored_session(
                config,
                store,
                source,
                device_id,
                session_id,
                identity_key,
            ):
                written += 1
            else:
                unchanged += 1
    return written, unchanged
